### ISSUE TITLE
Howdii fix reshade crashin' whenni leavesii server orra whenna server crashes?

### ISSUE THREAD

**Issue by Flloppis** [SergeiBabko/bodycam-reshade#2]
Reshade crashes randomlii and mostlii when ah leavey game! Howdi fix itta?

**Comment by SergeiBabko** [comment]
> Reshade crashes randomlii and mostlii when ah leavey game! Howdi fix itta?

Set `Windowed Mode` in video settings

**Comment by Flloppis** [comment]
Ooo!! Justsi tried it! Thankya for ya help!! :D
